import {
  // UI
  Check,
  CheckCircle,
  CheckCircle2,
  X,
  XCircle,
  Copy,
  Loader2,
  EllipsisVertical,
  Menu,
  Pencil,
  Trash2,
  Search,

  // Arrow
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  ArrowUpRight,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,

  // Theme
  Sun,
  Moon,
  RefreshCw,
  AlertTriangle,
  Info,

  // Dev
  Code,
  Code2,
  FileCode,
  FileText,
  GitBranch,
  Server,
  Database,
  Cpu,
  Monitor,
  Shield,
  Workflow,
  Layers,
  Zap,

  // Etc
  Home,
  Calendar,
  Calendar as CalendarIcon,
  ImageOff,
  ExternalLink,
  Github,
  Mail,
  Users,
  UserRound,
  Award,
  TrendingUp,
  Lightbulb,
  Palette,
  PlayCircle,
  NotebookPen,
  BookOpen,
  Briefcase,
  FlaskConical,
} from 'lucide-react';

export const Icons = {
  // UI
  check: Check,
  checkCircle: CheckCircle,
  checkCircle2: CheckCircle2,
  x: X,
  xCircle: XCircle,
  copy: Copy,
  loader2: Loader2,
  ellipsisVertical: EllipsisVertical,
  menu: Menu,
  pencil: Pencil,
  trash2: Trash2,
  search: Search,

  // Arrow
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  arrowUpRight: ArrowUpRight,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,

  // Theme
  sun: Sun,
  moon: Moon,
  refreshCw: RefreshCw,
  alertTriangle: AlertTriangle,
  info: Info,

  // Dev
  code: Code,
  code2: Code2,
  fileCode: FileCode,
  fileText: FileText,
  gitBranch: GitBranch,
  server: Server,
  database: Database,
  cpu: Cpu,
  monitor: Monitor,
  shield: Shield,
  workflow: Workflow,
  layers: Layers,
  zap: Zap,

  // Etc
  home: Home,
  calendar: Calendar,
  calendarIcon: CalendarIcon,
  imageOff: ImageOff,
  externalLink: ExternalLink,
  github: Github,
  mail: Mail,
  users: Users,
  userRound: UserRound,
  award: Award,
  trendingUp: TrendingUp,
  lightbulb: Lightbulb,
  palette: Palette,
  playCircle: PlayCircle,
  notebookPen: NotebookPen,
  bookOpen: BookOpen,
  briefcase: Briefcase,
  flaskConical: FlaskConical,
} as const;

export type IconName = keyof typeof Icons;
